#!/bin/bash

while getopts ":d:f:" opt; do
  case $opt in
    d) domain="$OPTARG"
    ;;
    f) folder="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    echo "Command ended with return code 0"
    exit 0
    ;;
  esac
done

if [ -z "$domain" ]
then
      echo "Error: Parameter -d is empty"
      exit 0
fi

if [ -z "$folder" ]
then
	echo "Error: parameter -f is empty"
	exit 0
fi

echo "Copying certificates from /etc/letsencrypt/archive/$folder to /etc/letsencrypt/archive/certs"


cp /etc/letsencrypt/archive/$folder/privkey1.pem /etc/letsencrypt/archive/certs/$domain.key


cp /etc/letsencrypt/archive/$folder/fullchain1.pem /etc/letsencrypt/archive/certs/$domain.crt


cp /etc/letsencrypt/archive/$folder/cert1.pem /etc/letsencrypt/archive/certs/$domain.chain.pem
